print("InshahAllah world best devops enginer")
print("new changes is here")
print("InshahAllah world best devops enginer")
print("InshahAllah world best devops enginer")
print("InshahAllah world best devops enginer")
